version: '3'
services:
  app:
    build: .
    ports:
      - "3031:3031"
    environment:
      MONGODB_URI: mongodb://mongodb/nft-shop
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db